# Laboratory work №4 
## ITERATIVE METHODS FOR LINEAR SYSTEM
In this laboratory work, you will get to know iterative methods for
solving linear system, Jacobi iteration and Seidel method as well as find
out how to solve the given linear system at the accuracy of eps= $10^-3$ .


Procedure
1. Reduce the system of equations to the form suitable for the Jacobi
method.
2. Solve the system of algebraic equations by Jacobi and Seidel
methods.
3. Solve the system of equations by the Jacobi method with
MATLAB and MathCAD. Save the obtained number of iterations.
4. Find the approximate solution to the system of equations by the
Seidel method with MATLAB and MathCAD. Save the obtained number of
iterations.
6. Compare the obtained results. Check whether the results are
correct by means of built-in functions.
5. Create a MATLAB script with dialog boxes for choosing solution
methods and defining input/output data.
Plan for students' reports


### Plan for students' reports
1. Procedure.
2. Theoretical background.
3. Hand calculations including five iterations for solving the given
system by the Jacobi method and the Seidel methods.
4. Calculations.
5. Conclusions.

### Theoretical background
Linear equation system is a set of linear equations to be solved simultaneously.  
A linear equation takes the form $a1x1+ a1x1+ a1x1+…+ a1x1=b$,    
where $n+1$ coefficients $a1,a2,…,an$ and $b$ are constants and $x1,x2,…,xn$ are   
unknowns. Thus, a system of linear equations can be denoted as 

<a><img src="https://image.ibb.co/jH0JN8/matrix.png" alt="matrix" border="0" /></a>


This system consists of m linear equations, each with n+1
coefficients, and has n unknowns; solutions to these equations must be
found simultaneously. To simplify the notation, it is possible to rewrite the
above equations as a matrix: A*x=b.   
The elements of the m x n matrix A are equation coefficients a(i,j) and
vectors x and b have the elements x(j) and bi respectively. Here, each line
forms a linear equation.
In order for a solution x to be unique, there must be at least as many
equations as unknowns. In terms of matrix, this means that .
However, if a system contains more equations than unknowns (m>=n ) it
is very likely (not to say the rule) that there exists no solution at all. Such
systems are called over-determined since they have more equations than
unknowns. They require special mathematical methods to be solved
approximately. The most common one is the least squares method which
aims at minimizing the sum of the error-squares made in each unknown
when trying to solve a system. Such problems usually occur when
measuring or fitting data.
It is easy to solve a system A ∗ x ൌ b in terms of linear algebra: You
only multiply the system by A-1 (inverse matrix) (from the left, resulting in
x= A-1b. However, except for trivial cases, it is very difficult to find A-1
. When a system of equations is large, iterative methods of solving
equations are more advantageous. Elimination methods, such as
Gaussian elimination, are prone to large round-off errors for a large set of
equations. Iterative methods, such as Jacobi and Seidel methods, give
the user control of the round-off error.
#### Jacobi iteration  (method of simple iteration).
This is the simplest
iterative method for solving systems of linear equations. This method is
the extension to the fixed-point iteration method that applies to systems of
linear equations.
<a><img src="https://preview.ibb.co/ix6xFT/matrix2.png" alt="matrix2" border="0" /></a>


<a><img src="https://preview.ibb.co/ndQAKo/matrix3.png" alt="matrix3" border="0"></a>

Thus, by the method of simple iteration, the approximation $X^k + 1$ 
 is
calculated for the previous approximation $X^k$ by substituting $X^k$ to
the right side of (4.2): 

<a><img src="https://image.ibb.co/cQ9LKo/matrix3.png" alt="matrix3" border="0"></a>

It is proved that if the sequence of vectors $X^k$ has a limit k-> to infinity,
this limit is a solution for (4.3).
Sufficient condition for convergence is a simple condition, that is:
any harmonized norm of the matrix C should be less than one.   
|C|<1

Hence, in order for the simple iteration method to converge for the
equations system X =CX+ F, it is sufficient that the one of the conditions
is fulfilled:

<a><img src="https://preview.ibb.co/hus4C8/Untitled.png" alt="Untitled" border="0"></a>

In practice, we usually adhere to the first or the second condition.
The inequalities will be satisfied if modules of diagonal elements for every
equation of the original system (4.1) are greater than the sum of absolute
values of all other coefficients (not including free members).
However, this condition is sufficient, but not necessary. In other words,
there are systems for which this condition is not met, but iterative process
still converges. 
The initial vector $X^(0)$ can be chosen arbitrarily. Sometimes, it can
be taken as  $X^(0)$->b .
However, the most useful initial approximation is to
take the approximate values of the unknowns obtained rough estimate.
To achieve the necessary accuracy , iterations must continue as
long as the condition are not fulfilled 

<a><img src="https://preview.ibb.co/jnvPC8/1.png" alt="1" border="0"></a>

So, in numerical linear algebra, Jacobi method is an algorithm for
determining solutions for a system of linear equations with the largest
absolute values in each row and column dominated by diagonal element.
Each diagonal element is solved for, and an approximate value is plugged
in. The process is then iterated until it converges. This algorithm is a
stripped-down version of the Jacobi transformation method of matrix
diagonalization
Seidel iteration is similar to the Jacobi method. Though it can be
applied to any matrix with non-zero elements on the diagonals,
convergence is only guaranteed if the matrix is either diagonally dominant,
or symmetric and positive definite. Seidel method is used to solve the left
side of the expression for x, using previous values of x in the right side,
but the elements of x(k+1) can be computed sequentially using forward
substitution by the following formulas: 
<a ><img src="https://image.ibb.co/kDfrs8/2.png" alt="2" border="0"></a>

The procedure generally continues until changes made by iterations
fall below a certain tolerance, such as a sufficiently small residual.
For the convergence of the Seidel method, it is enough to satisfy
one of conditions: 


<a><img src="https://preview.ibb.co/b8G0Ko/113.png" alt="113" border="0"></a>

Recommendations for the application of the Seidel method are the
same as those for the method of simple iteration. 

## Example of solving the system by Gaussian in Python 


In [ ]:
for k in range(n-1):
        #Choose largest pivot element below (and including) k
        maxindex = abs(A[k:,k]).argmax() + k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Swap rows
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            b[[k,maxindex]] = b[[maxindex, k]]
        for row in range(k+1, n):
            multiplier = A[row][k]/A[k][k]
            #the only one in this column since the rest are zero
            A[row][k] = multiplier
            for col in range(k + 1, n):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[k]

## Your task for laboratory work
<a><img src="https://preview.ibb.co/fmjQsJ/1.png" alt="1" border="0"></a>

# All program


In [4]:
import numpy as np
import numpy

def GENP(A, b):
    '''
    Gaussian elimination with no pivoting.
    % input: A is an n x n nonsingular matrix
    %        b is an n x 1 vector
    % output: x is the solution of Ax=b.
    % post-condition: A and b have been modified. 
    '''
    n =  len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A & b.", b.size, n)
    for pivot_row in range(n-1):
        for row in range(pivot_row+1, n):
            multiplier = A[row][pivot_row]/A[pivot_row][pivot_row]
            #the only one in this column since the rest are zero
            A[row][pivot_row] = multiplier
            for col in range(pivot_row + 1, n):
                A[row][col] = A[row][col] - multiplier*A[pivot_row][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[pivot_row]
    print (A)
    print (b)
    x = np.zeros(n)
    k = n-1
    x[k] = b[k]/A[k,k]
    while k >= 0:
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
        k = k-1
    return x

def GEPP(A, b):
    '''
    Gaussian elimination with partial pivoting.
    % input: A is an n x n nonsingular matrix
    %        b is an n x 1 vector
    % output: x is the solution of Ax=b.
    % post-condition: A and b have been modified. 
    '''
    n =  len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A & b.", b.size, n)
    # k represents the current pivot row. Since GE traverses the matrix in the upper 
    # right triangle, we also use k for indicating the k-th diagonal column index.
    for k in range(n-1):
        #Choose largest pivot element below (and including) k
        maxindex = abs(A[k:,k]).argmax() + k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Swap rows
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            b[[k,maxindex]] = b[[maxindex, k]]
        for row in range(k+1, n):
            multiplier = A[row][k]/A[k][k]
            #the only one in this column since the rest are zero
            A[row][k] = multiplier
            for col in range(k + 1, n):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[k]
    print (A)
    print (b)
    x = np.zeros(n)
    k = n-1
    x[k] = b[k]/A[k,k]
    while k >= 0:
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
        k = k-1
    return x

if __name__ == "__main__":
    A = np.array([[1.,-1.,1.,-1.],
                  [1.,0.,0.,0.],
                  [1.,1.,1.,1.],
                  [1.,2.,4.,8.]])
    b =  np.array([[14.],[4.],[2.],[2.]])
    print (GENP(np.copy(A), np.copy(b)))
    print ("Answer = ",GEPP(A,b))

[[ 1. -1.  1. -1.]
 [ 1.  1. -1.  1.]
 [ 1.  2.  2.  0.]
 [ 1.  3.  3.  6.]]
[[ 14.]
 [-10.]
 [  8.]
 [ -6.]]
[ 4. -5.  4. -1.]
[[ 1.         -1.          1.         -1.        ]
 [ 1.          3.          3.          9.        ]
 [ 1.          0.66666667 -2.         -4.        ]
 [ 1.          0.33333333  1.          2.        ]]
[[ 14.]
 [-12.]
 [ -4.]
 [ -2.]]
Answer =  [ 4. -5.  4. -1.]
